#!/usr/bin/env python3

import os
from os.path import expanduser

os.chdir(expanduser("~") + "/elastio")

os.system("cargo run -p aws-gc -- destroy --regions us-east-2 --tag=\"elastio:resource\" --expires-at-tag-id-pattern=elastio --skip alias key")
os.system("cargo run -p aws-gc -- destroy --regions us-east-2 --tag=\"elastio:resource\" --expires-at-tag-id-pattern=elastio --skip alias key")

os.system("cargo run --bin aws-gc -- destroy --tag elastio:resource --id-pattern elastio -s alias key")
os.system("cargo run --bin aws-gc -- destroy --tag elastio:resource --id-pattern elastio -s alias key")
