#!/usr/bin/env python3
import os
import sys
import platform

import File
import Debug
import Shell
import System


def open(path="."):
    if System.is_windows:
        Shell.run(["explorer", path])
    elif System.is_mac:
        Shell.run(["open", path])
    elif System.is_linux:
        print("NOT IMPLEMENTED ON THIS PLATFORM")
    else:
        print("Unknwn os")


files = File.get_files()
extensions = map(lambda f: File.extension(f), files)


for file in files:
    extension = File.extension(file)

    if extension == ".xcworkspace":
        open(file)
        exit()

    if extension == ".xcodeproj":
        open(file)
        exit()

open()
