
Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  config.vm.define "lin" do |lin|
    lin.vm.box = "generic/ubuntu2204"
  end
 
  config.vm.define "win" do |win|
    win.vm.box = "gusztavvargadr/windows-10"
  end

end
