
# Tells us if the host system is an Apple Silicon Mac running Rosetta
def is_arm64()
  `uname -m` == "arm64" || `/usr/bin/arch -64 sh -c "sysctl -in sysctl.proc_translated"`.strip() == "0"
end

Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true

  if is_arm64()
    config.vm.provider "parallels" do |v|
      v.memory = 1024 * 8
      v.cpus = 4
    end
  else
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024 * 4
      v.cpus = 4
    end
  end

  config.vm.define "lin" do |lin|
    if is_arm64()
      lin.vm.box = "jharoian3/ubuntu-22.04-arm64"
    else
      lin.vm.box = "generic/ubuntu2204"
    end
  end

  config.vm.define "win" do |win|
    if is_arm64()
      win.vm.box = "nullx/windows-arm64"
    else
      win.vm.box = "gusztavvargadr/visual-studio"
    end
  end

  config.vm.define "free" do |free|
    if is_arm64()
      free.vm.box = "nullx/windows-arm64"
    else
      free.vm.box = "generic/freebsd12"
    end
  end

end

# vagrant plugin install vagrant-parallels
