
Vagrant.configure("2") do |config|

  config.vm.define "win" do |v|   
    v.vm.box = "gusztavvargadr/windows-10" 
    v.cpus = 8
    v.memory = 16024  
  end

  config.vm.define "mac" do |v|   
    v.vm.box = "monsenso/macos-10.13"
    v.cpus = 8
    v.memory = 16024  
  end

  config.vm.define "lin" do |v|   
    v.vm.box = "generic/ubuntu2010"
    v.cpus = 8
    v.memory = 16024  
  end

end
