[package]
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
edition = "2024"
name = "push"
version = "0.1.0"

[[bin]]
name = "push"
path = "src/push.rs"

[dependencies]
anyhow = { workspace = true }
structopt = { workspace = true }

command = { workspace = true }
