[package]
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
edition = "2024"
name = "clone"
version = "0.1.0"

[[bin]]
name = "clone"
path = "src/clone.rs"

[dependencies]
anyhow = { workspace = true }
structopt = { workspace = true }
