[package]
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
edition = "2024"
name = "command"
version = "0.1.0"

[lib]
name = "command"
path = "src/command.rs"

[dependencies]
anyhow = { workspace = true }
